[package]
authors = ["Praveen Perera <praveen@avencera.com>"]
edition = "2018"
name = "rustywind"
version = "0.13.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cli
clap = {version = "3.0", features = ["cargo"]}
indoc = "1.0"

# files
ignore = "0.4"

# utils
itertools = "0.10"
once_cell = "1.9"

# string matching
aho-corasick = "0.7"
regex = "1"

# logging
env_logger = "0.9"
log = "0.4"

# parallel
rayon = "1.5"

[dev-dependencies]
pretty_assertions = "1.0"

[profile.release]
lto = true
